# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c84f8c98112534892731277df2905ce217e671a194f54feb0145cde813d8371161f28bad31e592e80830d82b26d87c90c48badf69bcfd76911a8b2c8e4a5a1f

test:
  secret_key_base: 63b2164201e23453fa31afd699d68b681a0abdc9fc23f3ac59eeb9695a078ce3a4b8e63d4aa0c21ab1c372692fb9b41623f2ed398947c784defda95556cc15af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
